### ISSUE TITLE
how to improve 

### ISSUE THREAD

**Issue by Liuqiyuan670** [RuisongZhou/RetinaFace.pytorch#1]
您做了许多尝试，但都没有提高，我想知道提高性能应从哪里入手呢？我试图为resnet50加cbam，结果没有更好。ghosnet加预训练模型会好一些吗

**Comment by RuisongZhou** [comment]
您好，我做的实验都是为了在减小精度损失的情况下加速。如果想要提高精度，可以参考DSFD模型
